from django.core.management.base import BaseCommand
from services.models import Service

SERVICES = [
    {"title":"Anxiety & Stress Relief","slug":"anxiety-stress-relief","category":"anxiety","icon":"fa-brain","color":"#7c6af7","tagline":"Calm the storm within. Find lasting peace.","problem":"Anxiety and chronic stress have become epidemic in modern life. Persistent worry, racing thoughts, physical tension and panic attacks can make daily life feel overwhelming. Many people feel trapped in a cycle of stress they cannot escape.","process":"Our hypnotherapy approach works directly with the subconscious mind to rewire stress response patterns. Through deep relaxation, guided visualisation and neuro-linguistic reprogramming, we help you release accumulated tension and build resilience at the deepest level.","outcomes":"Reduced anxiety within 2-3 sessions\nBetter sleep and physical relaxation\nCalmer responses to triggers\nImproved focus and mental clarity\nLong-lasting emotional regulation","duration":"6 sessions over 6 weeks","sessions_count":6,"price":2500,"is_featured":True,"order":1},
    {"title":"Smoking Cessation","slug":"smoking-cessation","category":"smoking","icon":"fa-ban","color":"#f4845f","tagline":"Break free from the habit. Reclaim your breath.","problem":"Smoking addiction is deeply rooted in the subconscious mind. While the conscious mind knows the harm, the subconscious clings to smoking as a coping mechanism. Willpower alone rarely works long-term.","process":"Using hypnotic suggestion and aversion therapy, we reprogram subconscious associations with smoking. We replace cravings with feelings of freedom and pride in your health. Clients receive personalised coping strategies for trigger situations.","outcomes":"Cessation within 1-3 sessions for most clients\nElimination of cravings\nPositive non-smoker identity shift\nReduced withdrawal symptoms\nImproved lung health within weeks","duration":"3-4 sessions over 3 weeks","sessions_count":3,"price":3000,"is_featured":True,"order":2},
    {"title":"Weight Loss Hypnosis","slug":"weight-loss-hypnosis","category":"weight","icon":"fa-leaf","color":"#4ecdc4","tagline":"Transform your relationship with food. From the inside out.","problem":"Emotional eating, food cravings, and negative body image are all subconscious patterns. Diets fail because they address only the conscious level. The real battle is in the mind.","process":"We use Virtual Gastric Band hypnosis, appetite reprogramming, and body-image visualisation. Sessions address emotional triggers behind overeating and install healthier food relationships.","outcomes":"Reduced appetite and natural portion control\nElimination of emotional eating triggers\nPositive body image and self-acceptance\nSustained motivation for lifestyle change\nAverage 2-4kg loss per month","duration":"8 sessions over 10 weeks","sessions_count":8,"price":2800,"is_featured":False,"order":3},
    {"title":"Sleep Improvement","slug":"sleep-improvement","category":"sleep","icon":"fa-moon-o","color":"#c9a84c","tagline":"Surrender to deep, healing sleep every night.","problem":"Insomnia, restless nights and racing thoughts at bedtime affect millions. Poor sleep cascades into mood, productivity, immunity and relationships. Most sleep issues stem from an overactive nervous system.","process":"Through sleep hypnosis, progressive relaxation and bedtime ritual programming, we quiet the overactive mind. We work with the subconscious to associate bed with deep relaxation and install a new sleep identity.","outcomes":"Falling asleep within minutes\nUninterrupted deep sleep cycles\nWaking refreshed and energised\nReduced night-time anxiety\nCustom sleep hypnosis audio provided","duration":"4 sessions over 4 weeks","sessions_count":4,"price":2200,"is_featured":False,"order":4},
    {"title":"Confidence Building","slug":"confidence-building","category":"confidence","icon":"fa-star","color":"#f9c74f","tagline":"Step into your power. Own every room you enter.","problem":"Low self-esteem, imposter syndrome, social anxiety and fear of failure are subconscious programs. They silently sabotage careers, relationships and personal fulfilment.","process":"We use ego-strengthening hypnosis, inner-child healing, and future-self visualisation to rebuild confidence from the subconscious roots. Sessions dissolve limiting beliefs and rehearse confident behaviour in the mind.","outcomes":"Genuine self-belief that feels natural\nComfort in social and professional situations\nElimination of imposter syndrome\nStronger personal boundaries\nClear sense of purpose and identity","duration":"6 sessions over 7 weeks","sessions_count":6,"price":2500,"is_featured":True,"order":5},
    {"title":"Trauma Healing","slug":"trauma-healing","category":"trauma","icon":"fa-heart","color":"#f7a8c4","tagline":"Release the past. Heal from the inside. Live fully again.","problem":"Unresolved trauma lives in the body and subconscious mind. It surfaces as flashbacks, emotional numbness, hypervigilance, and self-protective patterns that no longer serve you.","process":"Using trauma-informed hypnotherapy and somatic awareness, we gently approach traumatic memories from a safe distance. We process and integrate experiences without re-traumatising, releasing stored emotional charge.","outcomes":"Reduction in flashbacks and triggers\nEmotional freedom from the past\nRebuilding of trust and safety\nImproved relationships and intimacy\nDeep sense of peace and self-compassion","duration":"8-10 sessions over 10 weeks","sessions_count":9,"price":3500,"is_featured":False,"order":6},
]

class Command(BaseCommand):
    help = "Seed default services"
    def handle(self, *args, **kwargs):
        for data in SERVICES:
            Service.objects.update_or_create(slug=data["slug"], defaults=data)
            self.stdout.write(f"  seeded: {data['title']}")
        self.stdout.write(self.style.SUCCESS("Done!"))
