# Generated by Django 6.0.2 on 2026-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety & Stress Relief'), ('smoking', 'Smoking Cessation'), ('weight', 'Weight Loss Hypnosis'), ('sleep', 'Sleep Improvement'), ('confidence', 'Confidence Building'), ('trauma', 'Trauma Healing')], max_length=30)),
                ('icon', models.CharField(default='fa-heart', max_length=50)),
                ('color', models.CharField(default='#7c6af7', max_length=20)),
                ('tagline', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('process', models.TextField()),
                ('outcomes', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('sessions_count', models.PositiveIntegerField(default=6)),
                ('price', models.DecimalField(decimal_places=2, default=2500.0, max_digits=8)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
